[project]
name = "sentiment-analysis"
version = "0.1.0"
description = "Sentiment analysis project for Indonesia AI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
]
